apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 22.x.x
      helm:
        valueFiles:
          - https://raw.githubusercontent.com/harshavardhanc/kargo-nginx/main/env/dev/values.yaml
    - repoURL: https://github.com/harshavardhanc/kargo-nginx.git
      targetRevision: main
      ref: my-values-repo
      path: env/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true