apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: nginx-pipeline
  namespace: kargo
---
# 1. Warehouse: Watches Bitnami Public Repo
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: bitnami-warehouse
  namespace: kargo
spec:
  project: nginx-pipeline
  subscriptions:
    - chart:
        repoURL: https://charts.bitnami.com/bitnami
        name: nginx
        # Watches for any version 18.x.x (Adjust as needed)
        semverConstraint: "^18.0.0"
  interval: 5m
---
# 2. Stage: Test
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo
spec:
  project: nginx-pipeline
  subscriptions:
    warehouse: bitnami-warehouse
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/harshavardhanc/kargo-nginx.git # <--- UPDATE THIS
        writeBranch: main
        # Kargo will edit the ArgoCD App manifest directly
        yaml:
          - path: argocd-apps/nginx-test.yaml
            key: spec.source.targetRevision
            value: Version
---
# 3. Stage: Prod
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo
spec:
  project: nginx-pipeline
  subscriptions:
    upstreamStages:
      - name: test
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/harshavardhanc/kargo-nginx.git # <--- UPDATE THIS
        writeBranch: main
        yaml:
          - path: argocd-apps/nginx-prod.yaml
            key: spec.source.targetRevision
            value: Version
